### ISSUE TITLE
FIX: コンフィグファイルのQuestion直下のオプションスキーマを任意の文字列で設定できるようにしたい

### ISSUE THREAD

**Issue by daylight55** [daylight55/yg#4]
コンフィグファイルの`questions`の下は固定ではなく、任意のスキーマとしたい。
現在の実装は`app`や`appName`、`env`、`cluster`が固定となっている。

```yaml
questions:
  something-1:
    prompt: "Something1  ?"
  something-2:
    prompt: "Something2 ?"
    type:
      dynamic:
        dependency_questions: ["something-1"]
```

コンフィグファイルの定義、`CLAUDE.md`の正当性を見直しつつ、任意のスキーマを受け入れられるよう実装を見直したい。
必要に応じてテストコードも修正して。
